# Generated by Django 3.2.12 on 2022-06-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0002_memos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memos',
            name='is_read',
        ),
        migrations.AddField(
            model_name='memos',
            name='read',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='memos',
            name='good',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
